server:
  port: 8080
spring:
  application:
    name: ojajae
  datasource:
    url: jdbc:postgresql://${DB_URL}:5432/ojajae
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 180000
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ojajae
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: postgresql
  cloud:
    aws:
      region: ap-northeast-2
      credentials:
        accessKey: ${AWS_S3_ACCESSKEY}
        secretKey: ${AWS_S3_SECRETKEY}
      s3:
        bucket: ${AWS_S3_BUCKET}
      stack:
        auto: false
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace