server:
  port: 8080
spring:
  application:
    name: ojajae
  datasource:
    url: jdbc:postgresql://${DB_URL}/ojajae
    driverClassName: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 180000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: validate
    show-sql: true
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace