server:
  port: 8080
spring:
  application:
    name: ojajae
  datasource:
    url: jdbc:mysql://${DB_URL}:3306/ojajae?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf8&character_set_server=utf8mb4&useSSL=false&serverTimezone=Asia/Seoul
    driverClassName: com.mysql.cj.jdbc.Driver
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 180000
  cloud:
    aws:
      region: ap-northeast-2
      credentials:
        accessKey: ${AWS_S3_ACCESSKEY}
        secretKey: ${AWS_S3_SECRETKEY}
      s3:
        bucket: ${AWS_S3_BUCKET}
      stack:
        auto: false
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_schema: ojajae
    hibernate:
      ddl-auto: validate
    show-sql: true
    database: mysql
jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiration-time: 86400000
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace